### PR TITLE
Add a helper class for sapling trades

### PR DESCRIPTION
**Pull request by haykam821**

### CODE REVIEW

**Comment by NeusFear** [comment]
If this is still needed can you base it on 1.17, else close please

**Comment by haykam821** [comment]
This pull request is needed for wandering trader sapling trades in Traverse and Terrestria.

**Comment by NeusFear** [comment]
Great, let's just target 1.17 for this then since I don't really want to spend time on an old version when we hardly have time to keep it updated right now.

**Comment by Prospector** [comment]
Thanks!

**Pull request merged**
