### PR TITLE
Initial port to 1.16.2

### PR DESCRIPTION
**Pull request by shartte**
What is most certainly broken are the biome builders, since they dynamically create configured features, which now MUST be registered with an ID. It'd be possible to register them at that point, but that would require access to the biome registry key.

I did this port essentially to get Cinderscapes to work on 1.16.2, and would also consider either using the fog density mixin here or the one in cinderscapes, but not both.

### CODE REVIEW

**Comment by shartte** [comment]
Feel free to hit me up on Fabricord if you want to discuss the details of this, next steps and how a painless migration to JSON biomes could look like in 1.17.

**Comment by shartte** [comment]
grafik
grafik
grafik
grafik
grafik

**Comment by NeusFear** [comment]
The fog density thing should be here, we were planning on refactoring Terraform to be modular similar to fapi and that's when all these types of things got merged in.

**Comment by shartte** [comment]
@NeusFear I think the version of that in this PR is better than my version in Cinderscapes.
Here it's an actual registry that would allow for multiple Biomes to register themselves, and it also skips more of the mixin for unregistered biomes.
In 1.17 it _might_ be possible to add custom fields to Biome JSONs, but this variant of ID based behavior will definitely continue to work too.

**Comment by NeusFear** [comment]
What we might do is go on with our plans to migrate terraform to modular and use your PR here as a baseline for porting those modules, then maybe we could keep you in the loop for reviewing what happens there as to keep things futureproof.

**Comment by shartte** [comment]
"Use it for parts" :-D

**Comment by NeusFear** [comment]
Essentially yes lol

**Comment by Prospector** [comment]
Thanks so much for doing this, and it has been included in our 1.16.3 rework on Terraform. It still needs modularization, but currently it's thrown in the `terraform-legacy-v0` module on the `terraform-api-experimental` maven group

**Pull request closed without merging**
